export const PASSWORD_HASH_SALT_ROUNDS = 10;

export const SIGNUP_RATE_LIMIT_MAX_ATTEMPTS = 5;
export const SIGNUP_RATE_LIMIT_WINDOW_DURATION = "15m";

export const EMAIL_VERIFICATION_COOKIE_MAX_AGE_MINUTES = 60;
export const EMAIL_VERIFICATION_CODE_EXPIRY_MINUTES = 60;

export const MAX_VERIFY_EMAIL_ATTEMPTS = 10;
export const VERIFY_EMAIL_WINDOW_MINUTES = 30;

export const MAX_LOGIN_ATTEMPTS = 5;
export const LOGIN_WINDOW_MINUTES = 30;

export const MAX_RESEND_VERIFICATION_EMAIL_ATTEMPTS = 1;
export const RESEND_VERIFICATION_EMAIL_WINDOW_MINUTES = 3;
