export const PASSWORD_HASH_SALT_ROUNDS = 10;

export const SIGNUP_RATE_LIMIT_MAX_ATTEMPTS = 5;
export const SIGNUP_RATE_LIMIT_WINDOW_DURATION = "15m";
export const SIGNUP_COOKIE_MAX_AGE_HOURS = 1;
export const SIGNUP_VERIFICATION_CODE_EXPIRY_HOURS = 1;
